#version 450

layout(set = 0, binding = 0, std430) readonly restrict buffer InBufferA
{
    vec4 data[];
}A;

layout(set = 0, binding = 1, std430) readonly restrict buffer InBufferB
{
    vec4 data[];
}B;

layout(set = 0, binding = 2, std430) writeonly restrict buffer OutBuffer
{
    vec4 data[];
}C;

layout(local_size_x = 128) in;
void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= A.data.length()) return;
    C.data[i] = A.data[i] + B.data[i];
}